#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_65873_mic")]
public partial class hospitalDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertmic_contact(mic_contact instance);
  partial void Updatemic_contact(mic_contact instance);
  partial void Deletemic_contact(mic_contact instance);
  partial void Insertmic_pay_bill(mic_pay_bill instance);
  partial void Updatemic_pay_bill(mic_pay_bill instance);
  partial void Deletemic_pay_bill(mic_pay_bill instance);
  partial void Insertmic_symptom_checker(mic_symptom_checker instance);
  partial void Updatemic_symptom_checker(mic_symptom_checker instance);
  partial void Deletemic_symptom_checker(mic_symptom_checker instance);
  partial void Insertmic_volunteer(mic_volunteer instance);
  partial void Updatemic_volunteer(mic_volunteer instance);
  partial void Deletemic_volunteer(mic_volunteer instance);
  partial void Insertmic_job_posting(mic_job_posting instance);
  partial void Updatemic_job_posting(mic_job_posting instance);
  partial void Deletemic_job_posting(mic_job_posting instance);
  partial void Insertmic_career_application(mic_career_application instance);
  partial void Updatemic_career_application(mic_career_application instance);
  partial void Deletemic_career_application(mic_career_application instance);
  partial void Insertmic_location(mic_location instance);
  partial void Updatemic_location(mic_location instance);
  partial void Deletemic_location(mic_location instance);
  partial void Insertmic_alert(mic_alert instance);
  partial void Updatemic_alert(mic_alert instance);
  partial void Deletemic_alert(mic_alert instance);
  partial void Insertmic_news_event(mic_news_event instance);
  partial void Updatemic_news_event(mic_news_event instance);
  partial void Deletemic_news_event(mic_news_event instance);
  partial void Insertmic_sendletter(mic_sendletter instance);
  partial void Updatemic_sendletter(mic_sendletter instance);
  partial void Deletemic_sendletter(mic_sendletter instance);
  partial void Insertmic_mailing_list(mic_mailing_list instance);
  partial void Updatemic_mailing_list(mic_mailing_list instance);
  partial void Deletemic_mailing_list(mic_mailing_list instance);
  partial void Insertmic_slider(mic_slider instance);
  partial void Updatemic_slider(mic_slider instance);
  partial void Deletemic_slider(mic_slider instance);
  partial void Insertmic_services_anson(mic_services_anson instance);
  partial void Updatemic_services_anson(mic_services_anson instance);
  partial void Deletemic_services_anson(mic_services_anson instance);
  partial void Insertmic_services_bingham(mic_services_bingham instance);
  partial void Updatemic_services_bingham(mic_services_bingham instance);
  partial void Deletemic_services_bingham(mic_services_bingham instance);
  partial void Insertmic_services_lady_minto(mic_services_lady_minto instance);
  partial void Updatemic_services_lady_minto(mic_services_lady_minto instance);
  partial void Deletemic_services_lady_minto(mic_services_lady_minto instance);
  partial void Insertmic_donation(mic_donation instance);
  partial void Updatemic_donation(mic_donation instance);
  partial void Deletemic_donation(mic_donation instance);
  partial void Insertmic_book_appointment(mic_book_appointment instance);
  partial void Updatemic_book_appointment(mic_book_appointment instance);
  partial void Deletemic_book_appointment(mic_book_appointment instance);
  #endregion
	
	public hospitalDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_65873_micConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public hospitalDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public hospitalDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public hospitalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public hospitalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<mic_contact> mic_contacts
	{
		get
		{
			return this.GetTable<mic_contact>();
		}
	}
	
	public System.Data.Linq.Table<mic_pay_bill> mic_pay_bills
	{
		get
		{
			return this.GetTable<mic_pay_bill>();
		}
	}
	
	public System.Data.Linq.Table<mic_symptom_checker> mic_symptom_checkers
	{
		get
		{
			return this.GetTable<mic_symptom_checker>();
		}
	}
	
	public System.Data.Linq.Table<mic_volunteer> mic_volunteers
	{
		get
		{
			return this.GetTable<mic_volunteer>();
		}
	}
	
	public System.Data.Linq.Table<mic_job_posting> mic_job_postings
	{
		get
		{
			return this.GetTable<mic_job_posting>();
		}
	}
	
	public System.Data.Linq.Table<mic_career_application> mic_career_applications
	{
		get
		{
			return this.GetTable<mic_career_application>();
		}
	}
	
	public System.Data.Linq.Table<mic_location> mic_locations
	{
		get
		{
			return this.GetTable<mic_location>();
		}
	}
	
	public System.Data.Linq.Table<mic_alert> mic_alerts
	{
		get
		{
			return this.GetTable<mic_alert>();
		}
	}
	
	public System.Data.Linq.Table<mic_news_event> mic_news_events
	{
		get
		{
			return this.GetTable<mic_news_event>();
		}
	}
	
	public System.Data.Linq.Table<mic_sendletter> mic_sendletters
	{
		get
		{
			return this.GetTable<mic_sendletter>();
		}
	}
	
	public System.Data.Linq.Table<mic_mailing_list> mic_mailing_lists
	{
		get
		{
			return this.GetTable<mic_mailing_list>();
		}
	}
	
	public System.Data.Linq.Table<mic_slider> mic_sliders
	{
		get
		{
			return this.GetTable<mic_slider>();
		}
	}
	
	public System.Data.Linq.Table<mic_services_anson> mic_services_ansons
	{
		get
		{
			return this.GetTable<mic_services_anson>();
		}
	}
	
	public System.Data.Linq.Table<mic_services_bingham> mic_services_binghams
	{
		get
		{
			return this.GetTable<mic_services_bingham>();
		}
	}
	
	public System.Data.Linq.Table<mic_services_lady_minto> mic_services_lady_mintos
	{
		get
		{
			return this.GetTable<mic_services_lady_minto>();
		}
	}
	
	public System.Data.Linq.Table<mic_donation> mic_donations
	{
		get
		{
			return this.GetTable<mic_donation>();
		}
	}
	
	public System.Data.Linq.Table<mic_book_appointment> mic_book_appointments
	{
		get
		{
			return this.GetTable<mic_book_appointment>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_contact")]
public partial class mic_contact : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _fname;
	
	private string _lname;
	
	private string _email;
	
	private string _city;
	
	private string _province;
	
	private string _subject;
	
	private string _message;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    #endregion
	
	public mic_contact()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(30)")]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(30)")]
	public string lname
	{
		get
		{
			return this._lname;
		}
		set
		{
			if ((this._lname != value))
			{
				this.OnlnameChanging(value);
				this.SendPropertyChanging();
				this._lname = value;
				this.SendPropertyChanged("lname");
				this.OnlnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(30)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(30)")]
	public string province
	{
		get
		{
			return this._province;
		}
		set
		{
			if ((this._province != value))
			{
				this.OnprovinceChanging(value);
				this.SendPropertyChanging();
				this._province = value;
				this.SendPropertyChanged("province");
				this.OnprovinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="VarChar(50)")]
	public string subject
	{
		get
		{
			return this._subject;
		}
		set
		{
			if ((this._subject != value))
			{
				this.OnsubjectChanging(value);
				this.SendPropertyChanging();
				this._subject = value;
				this.SendPropertyChanged("subject");
				this.OnsubjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(MAX)")]
	public string message
	{
		get
		{
			return this._message;
		}
		set
		{
			if ((this._message != value))
			{
				this.OnmessageChanging(value);
				this.SendPropertyChanging();
				this._message = value;
				this.SendPropertyChanged("message");
				this.OnmessageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_pay_bills")]
public partial class mic_pay_bill : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _fname;
	
	private string _lname;
	
	private string _address;
	
	private string _city;
	
	private string _province;
	
	private string _zip;
	
	private string _phone;
	
	private string _email;
	
	private System.Nullable<decimal> _amount;
	
	private string _card_type;
	
	private string _card_number;
	
	private string _security_number;
	
	private string _cardholder_name;
	
	private System.Nullable<System.DateTime> _expiration;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnamountChanging(System.Nullable<decimal> value);
    partial void OnamountChanged();
    partial void Oncard_typeChanging(string value);
    partial void Oncard_typeChanged();
    partial void Oncard_numberChanging(string value);
    partial void Oncard_numberChanged();
    partial void Onsecurity_numberChanging(string value);
    partial void Onsecurity_numberChanged();
    partial void Oncardholder_nameChanging(string value);
    partial void Oncardholder_nameChanged();
    partial void OnexpirationChanging(System.Nullable<System.DateTime> value);
    partial void OnexpirationChanged();
    #endregion
	
	public mic_pay_bill()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(20)")]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(20)")]
	public string lname
	{
		get
		{
			return this._lname;
		}
		set
		{
			if ((this._lname != value))
			{
				this.OnlnameChanging(value);
				this.SendPropertyChanging();
				this._lname = value;
				this.SendPropertyChanged("lname");
				this.OnlnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(30)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(20)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(20)")]
	public string province
	{
		get
		{
			return this._province;
		}
		set
		{
			if ((this._province != value))
			{
				this.OnprovinceChanging(value);
				this.SendPropertyChanging();
				this._province = value;
				this.SendPropertyChanged("province");
				this.OnprovinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="VarChar(10)")]
	public string zip
	{
		get
		{
			return this._zip;
		}
		set
		{
			if ((this._zip != value))
			{
				this.OnzipChanging(value);
				this.SendPropertyChanging();
				this._zip = value;
				this.SendPropertyChanged("zip");
				this.OnzipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(10)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(20)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this.OnamountChanging(value);
				this.SendPropertyChanging();
				this._amount = value;
				this.SendPropertyChanged("amount");
				this.OnamountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_type", DbType="VarChar(20)")]
	public string card_type
	{
		get
		{
			return this._card_type;
		}
		set
		{
			if ((this._card_type != value))
			{
				this.Oncard_typeChanging(value);
				this.SendPropertyChanging();
				this._card_type = value;
				this.SendPropertyChanged("card_type");
				this.Oncard_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_number", DbType="VarChar(20)")]
	public string card_number
	{
		get
		{
			return this._card_number;
		}
		set
		{
			if ((this._card_number != value))
			{
				this.Oncard_numberChanging(value);
				this.SendPropertyChanging();
				this._card_number = value;
				this.SendPropertyChanged("card_number");
				this.Oncard_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_security_number", DbType="VarChar(20)")]
	public string security_number
	{
		get
		{
			return this._security_number;
		}
		set
		{
			if ((this._security_number != value))
			{
				this.Onsecurity_numberChanging(value);
				this.SendPropertyChanging();
				this._security_number = value;
				this.SendPropertyChanged("security_number");
				this.Onsecurity_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardholder_name", DbType="VarChar(20)")]
	public string cardholder_name
	{
		get
		{
			return this._cardholder_name;
		}
		set
		{
			if ((this._cardholder_name != value))
			{
				this.Oncardholder_nameChanging(value);
				this.SendPropertyChanging();
				this._cardholder_name = value;
				this.SendPropertyChanged("cardholder_name");
				this.Oncardholder_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expiration", DbType="Date")]
	public System.Nullable<System.DateTime> expiration
	{
		get
		{
			return this._expiration;
		}
		set
		{
			if ((this._expiration != value))
			{
				this.OnexpirationChanging(value);
				this.SendPropertyChanging();
				this._expiration = value;
				this.SendPropertyChanged("expiration");
				this.OnexpirationChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_symptom_checker")]
public partial class mic_symptom_checker : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _region;
	
	private string _area;
	
	private string _symptom;
	
	private string _causes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OnareaChanging(string value);
    partial void OnareaChanged();
    partial void OnsymptomChanging(string value);
    partial void OnsymptomChanged();
    partial void OncausesChanging(string value);
    partial void OncausesChanged();
    #endregion
	
	public mic_symptom_checker()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string region
	{
		get
		{
			return this._region;
		}
		set
		{
			if ((this._region != value))
			{
				this.OnregionChanging(value);
				this.SendPropertyChanging();
				this._region = value;
				this.SendPropertyChanged("region");
				this.OnregionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string area
	{
		get
		{
			return this._area;
		}
		set
		{
			if ((this._area != value))
			{
				this.OnareaChanging(value);
				this.SendPropertyChanging();
				this._area = value;
				this.SendPropertyChanged("area");
				this.OnareaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_symptom", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string symptom
	{
		get
		{
			return this._symptom;
		}
		set
		{
			if ((this._symptom != value))
			{
				this.OnsymptomChanging(value);
				this.SendPropertyChanging();
				this._symptom = value;
				this.SendPropertyChanged("symptom");
				this.OnsymptomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_causes", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string causes
	{
		get
		{
			return this._causes;
		}
		set
		{
			if ((this._causes != value))
			{
				this.OncausesChanging(value);
				this.SendPropertyChanging();
				this._causes = value;
				this.SendPropertyChanged("causes");
				this.OncausesChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_volunteer")]
public partial class mic_volunteer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _fname;
	
	private string _lname;
	
	private string _gender;
	
	private System.Nullable<int> _age;
	
	private string _contact_number;
	
	private string _email;
	
	private string _address;
	
	private string _city;
	
	private string _province;
	
	private string _qualification;
	
	private string _school_name;
	
	private System.Nullable<System.DateTime> _date;
	
	private string _resume;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    partial void Oncontact_numberChanging(string value);
    partial void Oncontact_numberChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OnqualificationChanging(string value);
    partial void OnqualificationChanged();
    partial void Onschool_nameChanging(string value);
    partial void Onschool_nameChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnresumeChanging(string value);
    partial void OnresumeChanged();
    #endregion
	
	public mic_volunteer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(20)")]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(20)")]
	public string lname
	{
		get
		{
			return this._lname;
		}
		set
		{
			if ((this._lname != value))
			{
				this.OnlnameChanging(value);
				this.SendPropertyChanging();
				this._lname = value;
				this.SendPropertyChanged("lname");
				this.OnlnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(20)")]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
	public System.Nullable<int> age
	{
		get
		{
			return this._age;
		}
		set
		{
			if ((this._age != value))
			{
				this.OnageChanging(value);
				this.SendPropertyChanging();
				this._age = value;
				this.SendPropertyChanged("age");
				this.OnageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_number", DbType="VarChar(10)")]
	public string contact_number
	{
		get
		{
			return this._contact_number;
		}
		set
		{
			if ((this._contact_number != value))
			{
				this.Oncontact_numberChanging(value);
				this.SendPropertyChanging();
				this._contact_number = value;
				this.SendPropertyChanged("contact_number");
				this.Oncontact_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(20)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(30)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(20)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(22)")]
	public string province
	{
		get
		{
			return this._province;
		}
		set
		{
			if ((this._province != value))
			{
				this.OnprovinceChanging(value);
				this.SendPropertyChanging();
				this._province = value;
				this.SendPropertyChanged("province");
				this.OnprovinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qualification", DbType="VarChar(200)")]
	public string qualification
	{
		get
		{
			return this._qualification;
		}
		set
		{
			if ((this._qualification != value))
			{
				this.OnqualificationChanging(value);
				this.SendPropertyChanging();
				this._qualification = value;
				this.SendPropertyChanged("qualification");
				this.OnqualificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_school_name", DbType="VarChar(40)")]
	public string school_name
	{
		get
		{
			return this._school_name;
		}
		set
		{
			if ((this._school_name != value))
			{
				this.Onschool_nameChanging(value);
				this.SendPropertyChanging();
				this._school_name = value;
				this.SendPropertyChanged("school_name");
				this.Onschool_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resume", DbType="VarChar(40)")]
	public string resume
	{
		get
		{
			return this._resume;
		}
		set
		{
			if ((this._resume != value))
			{
				this.OnresumeChanging(value);
				this.SendPropertyChanging();
				this._resume = value;
				this.SendPropertyChanged("resume");
				this.OnresumeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_job_postings")]
public partial class mic_job_posting : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _position;
	
	private string _location;
	
	private string _details;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OndetailsChanging(string value);
    partial void OndetailsChanged();
    #endregion
	
	public mic_job_posting()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string position
	{
		get
		{
			return this._position;
		}
		set
		{
			if ((this._position != value))
			{
				this.OnpositionChanging(value);
				this.SendPropertyChanging();
				this._position = value;
				this.SendPropertyChanged("position");
				this.OnpositionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string location
	{
		get
		{
			return this._location;
		}
		set
		{
			if ((this._location != value))
			{
				this.OnlocationChanging(value);
				this.SendPropertyChanging();
				this._location = value;
				this.SendPropertyChanged("location");
				this.OnlocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string details
	{
		get
		{
			return this._details;
		}
		set
		{
			if ((this._details != value))
			{
				this.OndetailsChanging(value);
				this.SendPropertyChanging();
				this._details = value;
				this.SendPropertyChanged("details");
				this.OndetailsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_career_application")]
public partial class mic_career_application : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _career_id;
	
	private string _fname;
	
	private string _lname;
	
	private string _address;
	
	private System.Nullable<int> _country;
	
	private System.Nullable<int> _province;
	
	private string _city;
	
	private string _zip;
	
	private string _phone;
	
	private string _email;
	
	private string _resume;
	
	private string _coverletter;
	
	private System.Nullable<int> _ques_status;
	
	private System.Nullable<int> _ques_crime;
	
	private System.Nullable<int> _ques_certificate;
	
	private System.Nullable<int> _skill_proficiency;
	
	private System.Nullable<int> _skill_experience;
	
	private string _reason;
	
	private string _comment;
	
	private System.Nullable<int> _consent;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncareer_idChanging(int value);
    partial void Oncareer_idChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncountryChanging(System.Nullable<int> value);
    partial void OncountryChanged();
    partial void OnprovinceChanging(System.Nullable<int> value);
    partial void OnprovinceChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnresumeChanging(string value);
    partial void OnresumeChanged();
    partial void OncoverletterChanging(string value);
    partial void OncoverletterChanged();
    partial void Onques_statusChanging(System.Nullable<int> value);
    partial void Onques_statusChanged();
    partial void Onques_crimeChanging(System.Nullable<int> value);
    partial void Onques_crimeChanged();
    partial void Onques_certificateChanging(System.Nullable<int> value);
    partial void Onques_certificateChanged();
    partial void Onskill_proficiencyChanging(System.Nullable<int> value);
    partial void Onskill_proficiencyChanged();
    partial void Onskill_experienceChanging(System.Nullable<int> value);
    partial void Onskill_experienceChanged();
    partial void OnreasonChanging(string value);
    partial void OnreasonChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OnconsentChanging(System.Nullable<int> value);
    partial void OnconsentChanged();
    #endregion
	
	public mic_career_application()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_career_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int career_id
	{
		get
		{
			return this._career_id;
		}
		set
		{
			if ((this._career_id != value))
			{
				this.Oncareer_idChanging(value);
				this.SendPropertyChanging();
				this._career_id = value;
				this.SendPropertyChanged("career_id");
				this.Oncareer_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="NVarChar(20)")]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="NVarChar(20)")]
	public string lname
	{
		get
		{
			return this._lname;
		}
		set
		{
			if ((this._lname != value))
			{
				this.OnlnameChanging(value);
				this.SendPropertyChanging();
				this._lname = value;
				this.SendPropertyChanged("lname");
				this.OnlnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="Int")]
	public System.Nullable<int> country
	{
		get
		{
			return this._country;
		}
		set
		{
			if ((this._country != value))
			{
				this.OncountryChanging(value);
				this.SendPropertyChanging();
				this._country = value;
				this.SendPropertyChanged("country");
				this.OncountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="Int")]
	public System.Nullable<int> province
	{
		get
		{
			return this._province;
		}
		set
		{
			if ((this._province != value))
			{
				this.OnprovinceChanging(value);
				this.SendPropertyChanging();
				this._province = value;
				this.SendPropertyChanged("province");
				this.OnprovinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(20)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="NVarChar(6)")]
	public string zip
	{
		get
		{
			return this._zip;
		}
		set
		{
			if ((this._zip != value))
			{
				this.OnzipChanging(value);
				this.SendPropertyChanging();
				this._zip = value;
				this.SendPropertyChanged("zip");
				this.OnzipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(20)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(20)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resume", DbType="NVarChar(20)")]
	public string resume
	{
		get
		{
			return this._resume;
		}
		set
		{
			if ((this._resume != value))
			{
				this.OnresumeChanging(value);
				this.SendPropertyChanging();
				this._resume = value;
				this.SendPropertyChanged("resume");
				this.OnresumeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coverletter", DbType="NVarChar(20)")]
	public string coverletter
	{
		get
		{
			return this._coverletter;
		}
		set
		{
			if ((this._coverletter != value))
			{
				this.OncoverletterChanging(value);
				this.SendPropertyChanging();
				this._coverletter = value;
				this.SendPropertyChanged("coverletter");
				this.OncoverletterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ques_status", DbType="Int")]
	public System.Nullable<int> ques_status
	{
		get
		{
			return this._ques_status;
		}
		set
		{
			if ((this._ques_status != value))
			{
				this.Onques_statusChanging(value);
				this.SendPropertyChanging();
				this._ques_status = value;
				this.SendPropertyChanged("ques_status");
				this.Onques_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ques_crime", DbType="Int")]
	public System.Nullable<int> ques_crime
	{
		get
		{
			return this._ques_crime;
		}
		set
		{
			if ((this._ques_crime != value))
			{
				this.Onques_crimeChanging(value);
				this.SendPropertyChanging();
				this._ques_crime = value;
				this.SendPropertyChanged("ques_crime");
				this.Onques_crimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ques_certificate", DbType="Int")]
	public System.Nullable<int> ques_certificate
	{
		get
		{
			return this._ques_certificate;
		}
		set
		{
			if ((this._ques_certificate != value))
			{
				this.Onques_certificateChanging(value);
				this.SendPropertyChanging();
				this._ques_certificate = value;
				this.SendPropertyChanged("ques_certificate");
				this.Onques_certificateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skill_proficiency", DbType="Int")]
	public System.Nullable<int> skill_proficiency
	{
		get
		{
			return this._skill_proficiency;
		}
		set
		{
			if ((this._skill_proficiency != value))
			{
				this.Onskill_proficiencyChanging(value);
				this.SendPropertyChanging();
				this._skill_proficiency = value;
				this.SendPropertyChanged("skill_proficiency");
				this.Onskill_proficiencyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skill_experience", DbType="Int")]
	public System.Nullable<int> skill_experience
	{
		get
		{
			return this._skill_experience;
		}
		set
		{
			if ((this._skill_experience != value))
			{
				this.Onskill_experienceChanging(value);
				this.SendPropertyChanging();
				this._skill_experience = value;
				this.SendPropertyChanged("skill_experience");
				this.Onskill_experienceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reason", DbType="NVarChar(50)")]
	public string reason
	{
		get
		{
			return this._reason;
		}
		set
		{
			if ((this._reason != value))
			{
				this.OnreasonChanging(value);
				this.SendPropertyChanging();
				this._reason = value;
				this.SendPropertyChanged("reason");
				this.OnreasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(MAX)")]
	public string comment
	{
		get
		{
			return this._comment;
		}
		set
		{
			if ((this._comment != value))
			{
				this.OncommentChanging(value);
				this.SendPropertyChanging();
				this._comment = value;
				this.SendPropertyChanged("comment");
				this.OncommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consent", DbType="Int")]
	public System.Nullable<int> consent
	{
		get
		{
			return this._consent;
		}
		set
		{
			if ((this._consent != value))
			{
				this.OnconsentChanging(value);
				this.SendPropertyChanging();
				this._consent = value;
				this.SendPropertyChanged("consent");
				this.OnconsentChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_locations")]
public partial class mic_location : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _name;
	
	private string _image;
	
	private string _description;
	
	private System.Nullable<decimal> _lat;
	
	private System.Nullable<decimal> _lng;
	
	private string _phone;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnlatChanging(System.Nullable<decimal> value);
    partial void OnlatChanged();
    partial void OnlngChanging(System.Nullable<decimal> value);
    partial void OnlngChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
	
	public mic_location()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(50)")]
	public string image
	{
		get
		{
			return this._image;
		}
		set
		{
			if ((this._image != value))
			{
				this.OnimageChanging(value);
				this.SendPropertyChanging();
				this._image = value;
				this.SendPropertyChanged("image");
				this.OnimageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lat", DbType="Decimal(18,12)")]
	public System.Nullable<decimal> lat
	{
		get
		{
			return this._lat;
		}
		set
		{
			if ((this._lat != value))
			{
				this.OnlatChanging(value);
				this.SendPropertyChanging();
				this._lat = value;
				this.SendPropertyChanged("lat");
				this.OnlatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lng", DbType="Decimal(18,12)")]
	public System.Nullable<decimal> lng
	{
		get
		{
			return this._lng;
		}
		set
		{
			if ((this._lng != value))
			{
				this.OnlngChanging(value);
				this.SendPropertyChanging();
				this._lng = value;
				this.SendPropertyChanged("lng");
				this.OnlngChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_alerts")]
public partial class mic_alert : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<System.DateTime> _date_alert;
	
	private string _short_alert;
	
	private string _long_alert;
	
	private string _title_alert;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Ondate_alertChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_alertChanged();
    partial void Onshort_alertChanging(string value);
    partial void Onshort_alertChanged();
    partial void Onlong_alertChanging(string value);
    partial void Onlong_alertChanged();
    partial void Ontitle_alertChanging(string value);
    partial void Ontitle_alertChanged();
    #endregion
	
	public mic_alert()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_alert", DbType="DateTime")]
	public System.Nullable<System.DateTime> date_alert
	{
		get
		{
			return this._date_alert;
		}
		set
		{
			if ((this._date_alert != value))
			{
				this.Ondate_alertChanging(value);
				this.SendPropertyChanging();
				this._date_alert = value;
				this.SendPropertyChanged("date_alert");
				this.Ondate_alertChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_alert", DbType="VarChar(MAX)")]
	public string short_alert
	{
		get
		{
			return this._short_alert;
		}
		set
		{
			if ((this._short_alert != value))
			{
				this.Onshort_alertChanging(value);
				this.SendPropertyChanging();
				this._short_alert = value;
				this.SendPropertyChanged("short_alert");
				this.Onshort_alertChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_long_alert", DbType="VarChar(MAX)")]
	public string long_alert
	{
		get
		{
			return this._long_alert;
		}
		set
		{
			if ((this._long_alert != value))
			{
				this.Onlong_alertChanging(value);
				this.SendPropertyChanging();
				this._long_alert = value;
				this.SendPropertyChanged("long_alert");
				this.Onlong_alertChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title_alert", DbType="NVarChar(MAX)")]
	public string title_alert
	{
		get
		{
			return this._title_alert;
		}
		set
		{
			if ((this._title_alert != value))
			{
				this.Ontitle_alertChanging(value);
				this.SendPropertyChanging();
				this._title_alert = value;
				this.SendPropertyChanged("title_alert");
				this.Ontitle_alertChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_news_events")]
public partial class mic_news_event : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<System.DateTime> _date;
	
	private string _title;
	
	private string _content;
	
	private string _img;
	
	private string _category;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    #endregion
	
	public mic_news_event()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(MAX)")]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="VarChar(MAX)")]
	public string content
	{
		get
		{
			return this._content;
		}
		set
		{
			if ((this._content != value))
			{
				this.OncontentChanging(value);
				this.SendPropertyChanging();
				this._content = value;
				this.SendPropertyChanged("content");
				this.OncontentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(30)")]
	public string img
	{
		get
		{
			return this._img;
		}
		set
		{
			if ((this._img != value))
			{
				this.OnimgChanging(value);
				this.SendPropertyChanging();
				this._img = value;
				this.SendPropertyChanged("img");
				this.OnimgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="VarChar(6)")]
	public string category
	{
		get
		{
			return this._category;
		}
		set
		{
			if ((this._category != value))
			{
				this.OncategoryChanging(value);
				this.SendPropertyChanging();
				this._category = value;
				this.SendPropertyChanged("category");
				this.OncategoryChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_sendletter")]
public partial class mic_sendletter : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _sendletter_id;
	
	private string _subject;
	
	private string _message;
	
	private string _image;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsendletter_idChanging(int value);
    partial void Onsendletter_idChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    #endregion
	
	public mic_sendletter()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendletter_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int sendletter_id
	{
		get
		{
			return this._sendletter_id;
		}
		set
		{
			if ((this._sendletter_id != value))
			{
				this.Onsendletter_idChanging(value);
				this.SendPropertyChanging();
				this._sendletter_id = value;
				this.SendPropertyChanged("sendletter_id");
				this.Onsendletter_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="NVarChar(50)")]
	public string subject
	{
		get
		{
			return this._subject;
		}
		set
		{
			if ((this._subject != value))
			{
				this.OnsubjectChanging(value);
				this.SendPropertyChanging();
				this._subject = value;
				this.SendPropertyChanged("subject");
				this.OnsubjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="NVarChar(MAX)")]
	public string message
	{
		get
		{
			return this._message;
		}
		set
		{
			if ((this._message != value))
			{
				this.OnmessageChanging(value);
				this.SendPropertyChanging();
				this._message = value;
				this.SendPropertyChanged("message");
				this.OnmessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50)")]
	public string image
	{
		get
		{
			return this._image;
		}
		set
		{
			if ((this._image != value))
			{
				this.OnimageChanging(value);
				this.SendPropertyChanging();
				this._image = value;
				this.SendPropertyChanged("image");
				this.OnimageChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_mailing_list")]
public partial class mic_mailing_list : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _mailing_id;
	
	private string _name;
	
	private string _email;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmailing_idChanging(int value);
    partial void Onmailing_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
	
	public mic_mailing_list()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mailing_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int mailing_id
	{
		get
		{
			return this._mailing_id;
		}
		set
		{
			if ((this._mailing_id != value))
			{
				this.Onmailing_idChanging(value);
				this.SendPropertyChanging();
				this._mailing_id = value;
				this.SendPropertyChanged("mailing_id");
				this.Onmailing_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_slider")]
public partial class mic_slider : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _img;
	
	private string _name;
	
	private string _link;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    #endregion
	
	public mic_slider()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(50)")]
	public string img
	{
		get
		{
			return this._img;
		}
		set
		{
			if ((this._img != value))
			{
				this.OnimgChanging(value);
				this.SendPropertyChanging();
				this._img = value;
				this.SendPropertyChanged("img");
				this.OnimgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(MAX)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(MAX)")]
	public string link
	{
		get
		{
			return this._link;
		}
		set
		{
			if ((this._link != value))
			{
				this.OnlinkChanging(value);
				this.SendPropertyChanging();
				this._link = value;
				this.SendPropertyChanged("link");
				this.OnlinkChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_services_anson")]
public partial class mic_services_anson : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _service;
	
	private string _unique;
	
	private string _location;
	
	private string _details;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnserviceChanging(string value);
    partial void OnserviceChanged();
    partial void OnuniqueChanging(string value);
    partial void OnuniqueChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OndetailsChanging(string value);
    partial void OndetailsChanged();
    #endregion
	
	public mic_services_anson()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string service
	{
		get
		{
			return this._service;
		}
		set
		{
			if ((this._service != value))
			{
				this.OnserviceChanging(value);
				this.SendPropertyChanging();
				this._service = value;
				this.SendPropertyChanged("service");
				this.OnserviceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[unique]", Storage="_unique", DbType="Char(3) NOT NULL", CanBeNull=false)]
	public string unique
	{
		get
		{
			return this._unique;
		}
		set
		{
			if ((this._unique != value))
			{
				this.OnuniqueChanging(value);
				this.SendPropertyChanging();
				this._unique = value;
				this.SendPropertyChanged("unique");
				this.OnuniqueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string location
	{
		get
		{
			return this._location;
		}
		set
		{
			if ((this._location != value))
			{
				this.OnlocationChanging(value);
				this.SendPropertyChanging();
				this._location = value;
				this.SendPropertyChanged("location");
				this.OnlocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string details
	{
		get
		{
			return this._details;
		}
		set
		{
			if ((this._details != value))
			{
				this.OndetailsChanging(value);
				this.SendPropertyChanging();
				this._details = value;
				this.SendPropertyChanged("details");
				this.OndetailsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_services_bingham")]
public partial class mic_services_bingham : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _service;
	
	private string _unique;
	
	private string _location;
	
	private string _details;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnserviceChanging(string value);
    partial void OnserviceChanged();
    partial void OnuniqueChanging(string value);
    partial void OnuniqueChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OndetailsChanging(string value);
    partial void OndetailsChanged();
    #endregion
	
	public mic_services_bingham()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string service
	{
		get
		{
			return this._service;
		}
		set
		{
			if ((this._service != value))
			{
				this.OnserviceChanging(value);
				this.SendPropertyChanging();
				this._service = value;
				this.SendPropertyChanged("service");
				this.OnserviceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[unique]", Storage="_unique", DbType="Char(3) NOT NULL", CanBeNull=false)]
	public string unique
	{
		get
		{
			return this._unique;
		}
		set
		{
			if ((this._unique != value))
			{
				this.OnuniqueChanging(value);
				this.SendPropertyChanging();
				this._unique = value;
				this.SendPropertyChanged("unique");
				this.OnuniqueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string location
	{
		get
		{
			return this._location;
		}
		set
		{
			if ((this._location != value))
			{
				this.OnlocationChanging(value);
				this.SendPropertyChanging();
				this._location = value;
				this.SendPropertyChanged("location");
				this.OnlocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string details
	{
		get
		{
			return this._details;
		}
		set
		{
			if ((this._details != value))
			{
				this.OndetailsChanging(value);
				this.SendPropertyChanging();
				this._details = value;
				this.SendPropertyChanged("details");
				this.OndetailsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_services_lady_minto")]
public partial class mic_services_lady_minto : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _service;
	
	private string _unique;
	
	private string _location;
	
	private string _details;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnserviceChanging(string value);
    partial void OnserviceChanged();
    partial void OnuniqueChanging(string value);
    partial void OnuniqueChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OndetailsChanging(string value);
    partial void OndetailsChanged();
    #endregion
	
	public mic_services_lady_minto()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string service
	{
		get
		{
			return this._service;
		}
		set
		{
			if ((this._service != value))
			{
				this.OnserviceChanging(value);
				this.SendPropertyChanging();
				this._service = value;
				this.SendPropertyChanged("service");
				this.OnserviceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[unique]", Storage="_unique", DbType="Char(3) NOT NULL", CanBeNull=false)]
	public string unique
	{
		get
		{
			return this._unique;
		}
		set
		{
			if ((this._unique != value))
			{
				this.OnuniqueChanging(value);
				this.SendPropertyChanging();
				this._unique = value;
				this.SendPropertyChanged("unique");
				this.OnuniqueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string location
	{
		get
		{
			return this._location;
		}
		set
		{
			if ((this._location != value))
			{
				this.OnlocationChanging(value);
				this.SendPropertyChanging();
				this._location = value;
				this.SendPropertyChanged("location");
				this.OnlocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_details", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string details
	{
		get
		{
			return this._details;
		}
		set
		{
			if ((this._details != value))
			{
				this.OndetailsChanging(value);
				this.SendPropertyChanging();
				this._details = value;
				this.SendPropertyChanged("details");
				this.OndetailsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_donation")]
public partial class mic_donation : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _donation_id;
	
	private string _fname;
	
	private string _lname;
	
	private string _address;
	
	private string _city;
	
	private string _province;
	
	private string _zip;
	
	private string _phone;
	
	private string _email;
	
	private string _survey;
	
	private string _comment;
	
	private System.Nullable<int> _amount;
	
	private string _payment_type;
	
	private string _card_number;
	
	private System.Nullable<int> _security_number;
	
	private string _cardholder_name;
	
	private string _expiration_month;
	
	private string _expiration_year;
	
	private string _country;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondonation_idChanging(int value);
    partial void Ondonation_idChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsurveyChanging(string value);
    partial void OnsurveyChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OnamountChanging(System.Nullable<int> value);
    partial void OnamountChanged();
    partial void Onpayment_typeChanging(string value);
    partial void Onpayment_typeChanged();
    partial void Oncard_numberChanging(string value);
    partial void Oncard_numberChanged();
    partial void Onsecurity_numberChanging(System.Nullable<int> value);
    partial void Onsecurity_numberChanged();
    partial void Oncardholder_nameChanging(string value);
    partial void Oncardholder_nameChanged();
    partial void Onexpiration_monthChanging(string value);
    partial void Onexpiration_monthChanged();
    partial void Onexpiration_yearChanging(string value);
    partial void Onexpiration_yearChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    #endregion
	
	public mic_donation()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donation_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int donation_id
	{
		get
		{
			return this._donation_id;
		}
		set
		{
			if ((this._donation_id != value))
			{
				this.Ondonation_idChanging(value);
				this.SendPropertyChanging();
				this._donation_id = value;
				this.SendPropertyChanged("donation_id");
				this.Ondonation_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="NVarChar(20)")]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="NVarChar(20)")]
	public string lname
	{
		get
		{
			return this._lname;
		}
		set
		{
			if ((this._lname != value))
			{
				this.OnlnameChanging(value);
				this.SendPropertyChanging();
				this._lname = value;
				this.SendPropertyChanged("lname");
				this.OnlnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(MAX)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(20)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="NVarChar(20)")]
	public string province
	{
		get
		{
			return this._province;
		}
		set
		{
			if ((this._province != value))
			{
				this.OnprovinceChanging(value);
				this.SendPropertyChanging();
				this._province = value;
				this.SendPropertyChanged("province");
				this.OnprovinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="NVarChar(6)")]
	public string zip
	{
		get
		{
			return this._zip;
		}
		set
		{
			if ((this._zip != value))
			{
				this.OnzipChanging(value);
				this.SendPropertyChanging();
				this._zip = value;
				this.SendPropertyChanged("zip");
				this.OnzipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(20)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(20)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_survey", DbType="NVarChar(50)")]
	public string survey
	{
		get
		{
			return this._survey;
		}
		set
		{
			if ((this._survey != value))
			{
				this.OnsurveyChanging(value);
				this.SendPropertyChanging();
				this._survey = value;
				this.SendPropertyChanged("survey");
				this.OnsurveyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(MAX)")]
	public string comment
	{
		get
		{
			return this._comment;
		}
		set
		{
			if ((this._comment != value))
			{
				this.OncommentChanging(value);
				this.SendPropertyChanging();
				this._comment = value;
				this.SendPropertyChanged("comment");
				this.OncommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount", DbType="Int")]
	public System.Nullable<int> amount
	{
		get
		{
			return this._amount;
		}
		set
		{
			if ((this._amount != value))
			{
				this.OnamountChanging(value);
				this.SendPropertyChanging();
				this._amount = value;
				this.SendPropertyChanged("amount");
				this.OnamountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment_type", DbType="NVarChar(20)")]
	public string payment_type
	{
		get
		{
			return this._payment_type;
		}
		set
		{
			if ((this._payment_type != value))
			{
				this.Onpayment_typeChanging(value);
				this.SendPropertyChanging();
				this._payment_type = value;
				this.SendPropertyChanged("payment_type");
				this.Onpayment_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_number", DbType="NVarChar(20)")]
	public string card_number
	{
		get
		{
			return this._card_number;
		}
		set
		{
			if ((this._card_number != value))
			{
				this.Oncard_numberChanging(value);
				this.SendPropertyChanging();
				this._card_number = value;
				this.SendPropertyChanged("card_number");
				this.Oncard_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_security_number", DbType="Int")]
	public System.Nullable<int> security_number
	{
		get
		{
			return this._security_number;
		}
		set
		{
			if ((this._security_number != value))
			{
				this.Onsecurity_numberChanging(value);
				this.SendPropertyChanging();
				this._security_number = value;
				this.SendPropertyChanged("security_number");
				this.Onsecurity_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardholder_name", DbType="NVarChar(20)")]
	public string cardholder_name
	{
		get
		{
			return this._cardholder_name;
		}
		set
		{
			if ((this._cardholder_name != value))
			{
				this.Oncardholder_nameChanging(value);
				this.SendPropertyChanging();
				this._cardholder_name = value;
				this.SendPropertyChanged("cardholder_name");
				this.Oncardholder_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expiration_month", DbType="NVarChar(20)")]
	public string expiration_month
	{
		get
		{
			return this._expiration_month;
		}
		set
		{
			if ((this._expiration_month != value))
			{
				this.Onexpiration_monthChanging(value);
				this.SendPropertyChanging();
				this._expiration_month = value;
				this.SendPropertyChanged("expiration_month");
				this.Onexpiration_monthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expiration_year", DbType="NVarChar(20)")]
	public string expiration_year
	{
		get
		{
			return this._expiration_year;
		}
		set
		{
			if ((this._expiration_year != value))
			{
				this.Onexpiration_yearChanging(value);
				this.SendPropertyChanging();
				this._expiration_year = value;
				this.SendPropertyChanged("expiration_year");
				this.Onexpiration_yearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(20)")]
	public string country
	{
		get
		{
			return this._country;
		}
		set
		{
			if ((this._country != value))
			{
				this.OncountryChanging(value);
				this.SendPropertyChanging();
				this._country = value;
				this.SendPropertyChanged("country");
				this.OncountryChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mic_book_appointment")]
public partial class mic_book_appointment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _fname;
	
	private string _lname;
	
	private string _address;
	
	private string _city;
	
	private string _province;
	
	private string _postal_code;
	
	private string _phone;
	
	private System.Nullable<System.DateTime> _date;
	
	private string _reason;
	
	private bool _booked;
	
	private string _date_string;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnfnameChanging(string value);
    partial void OnfnameChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnprovinceChanging(string value);
    partial void OnprovinceChanged();
    partial void Onpostal_codeChanging(string value);
    partial void Onpostal_codeChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void OnreasonChanging(string value);
    partial void OnreasonChanged();
    partial void OnbookedChanging(bool value);
    partial void OnbookedChanged();
    partial void Ondate_stringChanging(string value);
    partial void Ondate_stringChanged();
    #endregion
	
	public mic_book_appointment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fname", DbType="VarChar(30)")]
	public string fname
	{
		get
		{
			return this._fname;
		}
		set
		{
			if ((this._fname != value))
			{
				this.OnfnameChanging(value);
				this.SendPropertyChanging();
				this._fname = value;
				this.SendPropertyChanged("fname");
				this.OnfnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="VarChar(30)")]
	public string lname
	{
		get
		{
			return this._lname;
		}
		set
		{
			if ((this._lname != value))
			{
				this.OnlnameChanging(value);
				this.SendPropertyChanging();
				this._lname = value;
				this.SendPropertyChanged("lname");
				this.OnlnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(30)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_province", DbType="VarChar(30)")]
	public string province
	{
		get
		{
			return this._province;
		}
		set
		{
			if ((this._province != value))
			{
				this.OnprovinceChanging(value);
				this.SendPropertyChanging();
				this._province = value;
				this.SendPropertyChanged("province");
				this.OnprovinceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postal_code", DbType="VarChar(7)")]
	public string postal_code
	{
		get
		{
			return this._postal_code;
		}
		set
		{
			if ((this._postal_code != value))
			{
				this.Onpostal_codeChanging(value);
				this.SendPropertyChanging();
				this._postal_code = value;
				this.SendPropertyChanged("postal_code");
				this.Onpostal_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(15)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reason", DbType="VarChar(MAX)")]
	public string reason
	{
		get
		{
			return this._reason;
		}
		set
		{
			if ((this._reason != value))
			{
				this.OnreasonChanging(value);
				this.SendPropertyChanging();
				this._reason = value;
				this.SendPropertyChanged("reason");
				this.OnreasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_booked", DbType="Bit NOT NULL")]
	public bool booked
	{
		get
		{
			return this._booked;
		}
		set
		{
			if ((this._booked != value))
			{
				this.OnbookedChanging(value);
				this.SendPropertyChanging();
				this._booked = value;
				this.SendPropertyChanged("booked");
				this.OnbookedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_string", DbType="VarChar(50)")]
	public string date_string
	{
		get
		{
			return this._date_string;
		}
		set
		{
			if ((this._date_string != value))
			{
				this.Ondate_stringChanging(value);
				this.SendPropertyChanging();
				this._date_string = value;
				this.SendPropertyChanged("date_string");
				this.Ondate_stringChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
