<?xml version="1.0" encoding="utf-8"?><Database Name="DB_65873_mic" Class="hospitalDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=s10.winhost.com;Initial Catalog=DB_65873_mic;User ID=DB_65873_mic_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_65873_micConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.mic_book_appointment" Member="mic_book_appointments">
    <Type Name="mic_book_appointment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="postal_code" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="reason" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_contact" Member="mic_contacts">
    <Type Name="mic_contact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="subject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_donation" Member="mic_donations">
    <Type Name="mic_donation">
      <Column Name="donation_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="survey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="payment_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="card_number" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="security_number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cardholder_name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="expiration" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_find_service" Member="mic_find_services">
    <Type Name="mic_find_service">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="service" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="[unique]" Member="unique" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="location" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="details" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.mic_pay_bills" Member="mic_pay_bills">
    <Type Name="mic_pay_bill">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="card_type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="card_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="security_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="cardholder_name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="expiration" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_symptom_checker" Member="mic_symptom_checkers">
    <Type Name="mic_symptom_checker">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="region" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="area" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="symptom" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="causes" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.mic_volunteer" Member="mic_volunteers">
    <Type Name="mic_volunteer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contact_number" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(22)" CanBeNull="true" />
      <Column Name="qualification" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="school_name" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="resume" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_job_postings" Member="mic_job_postings">
    <Type Name="mic_job_posting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="position" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="location" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="details" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.mic_career_application" Member="mic_career_applications">
    <Type Name="mic_career_application">
      <Column Name="career_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="province" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="resume" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="coverletter" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ques_status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ques_crime" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ques_certificate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="skill_proficiency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="skill_experience" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="reason" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="consent" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_locations" Member="mic_locations">
    <Type Name="mic_location">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lat" Type="System.Decimal" DbType="Decimal(18,12)" CanBeNull="true" />
      <Column Name="lng" Type="System.Decimal" DbType="Decimal(18,12)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_alerts" Member="mic_alerts">
    <Type Name="mic_alert">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date_alert" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="short_alert" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="long_alert" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="title_alert" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_news_events" Member="mic_news_events">
    <Type Name="mic_news_event">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="img" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="category" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_slider" Member="mic_sliders">
    <Type Name="mic_slider">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="img_path" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="alt_name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_sendletter" Member="mic_sendletters">
    <Type Name="mic_sendletter">
      <Column Name="sendletter_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="subject" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mic_mailing_list" Member="mic_mailing_lists">
    <Type Name="mic_mailing_list">
      <Column Name="mailing_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>